/* Store catalogue. Demo data: prices and ratings are illustrative. Change BRAND to rename the store. */
const BRAND = { name: 'Jhatpat', eta: 11 };
const HERO = ["apple", "bread", "banana"];
const OFFERS = [
 {
  "title": "Fresh fruit, up to 25% off",
  "text": "Mangoes, apples, bananas and more.",
  "cta": "Shop fruits",
  "href": "#/c/fv/fruit",
  "img": "mango"
 },
 {
  "title": "Breakfast in ten minutes",
  "text": "Oats, bread, jam and honey.",
  "cta": "Shop breakfast",
  "href": "#/c/breakfast",
  "img": "honey"
 },
 {
  "title": "Something with your chai",
  "text": "Biscuits, cookies and namkeen.",
  "cta": "Shop snacks",
  "href": "#/c/snacks",
  "img": "digestive"
 }
];
const CATS = [
 {
  "id": "fv",
  "name": "Fruits & Vegetables",
  "img": "img/tomato.webp",
  "subs": [
   {
    "id": "veg",
    "name": "Fresh vegetables"
   },
   {
    "id": "fruit",
    "name": "Fresh fruits"
   },
   {
    "id": "herbs",
    "name": "Herbs & seasoning"
   }
  ]
 },
 {
  "id": "dairy",
  "name": "Dairy, Bread & Eggs",
  "img": "img/milk-bottle.webp",
  "subs": [
   {
    "id": "milk",
    "name": "Milk"
   },
   {
    "id": "butter",
    "name": "Butter, cheese & ghee"
   },
   {
    "id": "curd",
    "name": "Curd & paneer"
   },
   {
    "id": "bread",
    "name": "Bread & eggs"
   }
  ]
 },
 {
  "id": "snacks",
  "name": "Snacks & Biscuits",
  "img": "img/lays.webp",
  "subs": [
   {
    "id": "chips",
    "name": "Chips & namkeen"
   },
   {
    "id": "biscuits",
    "name": "Biscuits & cookies"
   }
  ]
 },
 {
  "id": "drinks",
  "name": "Cold Drinks & Juices",
  "img": "img/coca-cola.webp",
  "subs": [
   {
    "id": "soft",
    "name": "Soft drinks"
   },
   {
    "id": "juice",
    "name": "Juices & energy drinks"
   }
  ]
 },
 {
  "id": "breakfast",
  "name": "Breakfast & Instant Food",
  "img": "img/corn-flakes.webp",
  "subs": [
   {
    "id": "noodles",
    "name": "Noodles"
   },
   {
    "id": "cereal",
    "name": "Cereals & oats"
   },
   {
    "id": "spreads",
    "name": "Spreads & sauces"
   }
  ]
 },
 {
  "id": "staples",
  "name": "Atta, Rice & Dal",
  "img": "img/india-gate.webp",
  "subs": [
   {
    "id": "grains",
    "name": "Atta & rice"
   },
   {
    "id": "dal",
    "name": "Dal & pulses"
   },
   {
    "id": "oil",
    "name": "Oil & salt"
   },
   {
    "id": "masala",
    "name": "Masala & spices"
   }
  ]
 },
 {
  "id": "sweets",
  "name": "Chocolates & Ice Cream",
  "img": "img/kitkat.webp",
  "subs": [
   {
    "id": "choc",
    "name": "Chocolates"
   },
   {
    "id": "ice",
    "name": "Ice cream"
   }
  ]
 },
 {
  "id": "chai",
  "name": "Tea, Coffee & Dry Fruits",
  "img": "img/almonds.webp",
  "subs": [
   {
    "id": "tea",
    "name": "Tea"
   },
   {
    "id": "coffee",
    "name": "Coffee"
   },
   {
    "id": "dry",
    "name": "Dry fruits & nuts"
   }
  ]
 }
];
const PRODUCTS = [
 {
  "id": "tomato",
  "name": "Tomato",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 24,
  "mrp": 32,
  "img": "img/tomato.webp",
  "rating": 4.3,
  "reviews": "35.4k",
  "tags": "tamatar",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "onion",
  "name": "Onion",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "1 kg",
  "price": 38,
  "mrp": 49,
  "img": "img/onion.webp",
  "rating": 4.2,
  "reviews": "26.5k",
  "tags": "pyaz",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "potato",
  "name": "Potato",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "1 kg",
  "price": 32,
  "mrp": 40,
  "img": "img/potato.webp",
  "rating": 4.2,
  "reviews": "34.3k",
  "tags": "aloo",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "carrot",
  "name": "Carrot",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 35,
  "mrp": 45,
  "img": "img/carrot.webp",
  "rating": 4.7,
  "reviews": "39.8k",
  "tags": "gajar",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "cucumber",
  "name": "Cucumber",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 28,
  "mrp": 36,
  "img": "img/cucumber.webp",
  "rating": 4.5,
  "reviews": "29.8k",
  "tags": "kheera",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "spinach",
  "name": "Spinach",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "250 g",
  "price": 22,
  "mrp": 30,
  "img": "img/spinach.webp",
  "rating": 4.5,
  "reviews": "21.0k",
  "tags": "palak",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "broccoli",
  "name": "Broccoli",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "1 pc (approx. 300 g)",
  "price": 69,
  "mrp": 95,
  "img": "img/broccoli.webp",
  "rating": 4.1,
  "reviews": "33.2k",
  "tags": "",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "cabbage",
  "name": "Cabbage",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "1 pc (approx. 500 g)",
  "price": 29,
  "mrp": 38,
  "img": "img/cabbage.webp",
  "rating": 4.5,
  "reviews": "37.6k",
  "tags": "patta gobhi",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "capsicum",
  "name": "Red capsicum",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "250 g",
  "price": 59,
  "mrp": 80,
  "img": "img/capsicum.webp",
  "rating": 4.1,
  "reviews": "1.0k",
  "tags": "shimla mirch pepper",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "beetroot",
  "name": "Beetroot",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 34,
  "mrp": 45,
  "img": "img/beetroot.webp",
  "rating": 4.5,
  "reviews": "13.2k",
  "tags": "chukandar",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "brinjal",
  "name": "Brinjal",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 31,
  "mrp": 40,
  "img": "img/brinjal.webp",
  "rating": 4.8,
  "reviews": "8.7k",
  "tags": "baingan aubergine",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "mushroom",
  "name": "Button mushroom",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "200 g",
  "price": 49,
  "mrp": 60,
  "img": "img/mushroom.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "peas",
  "name": "Green peas",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "250 g",
  "price": 45,
  "mrp": 58,
  "img": "img/peas.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "matar",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "beans",
  "name": "French beans",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "250 g",
  "price": 33,
  "mrp": 42,
  "img": "img/beans.webp",
  "rating": 4.2,
  "reviews": "26.5k",
  "tags": "",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "pumpkin",
  "name": "Pumpkin",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "veg",
  "unit": "500 g",
  "price": 27,
  "mrp": 35,
  "img": "img/pumpkin.webp",
  "rating": 4.8,
  "reviews": "32.1k",
  "tags": "kaddu",
  "about": "Picked fresh and checked before packing. Wash well before use."
 },
 {
  "id": "banana",
  "name": "Banana",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "6 pcs",
  "price": 42,
  "mrp": 55,
  "img": "img/banana.webp",
  "rating": 4.8,
  "reviews": "8.7k",
  "tags": "kela",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "apple",
  "name": "Apple",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "4 pcs (approx. 600 g)",
  "price": 129,
  "mrp": 165,
  "img": "img/apple.webp",
  "rating": 4.1,
  "reviews": "9.8k",
  "tags": "seb",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "mango",
  "name": "Mango",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "2 pcs (approx. 500 g)",
  "price": 119,
  "mrp": 150,
  "img": "img/mango.webp",
  "rating": 4.5,
  "reviews": "5.4k",
  "tags": "aam",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "orange",
  "name": "Orange",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "4 pcs (approx. 600 g)",
  "price": 89,
  "mrp": 110,
  "img": "img/orange.webp",
  "rating": 4.1,
  "reviews": "9.8k",
  "tags": "santra",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "pineapple",
  "name": "Pineapple",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "1 pc",
  "price": 79,
  "mrp": 99,
  "img": "img/pineapple.webp",
  "rating": 4.8,
  "reviews": "40.9k",
  "tags": "ananas",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "strawberry",
  "name": "Strawberry",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "200 g",
  "price": 99,
  "mrp": 130,
  "img": "img/strawberry.webp",
  "rating": 4.8,
  "reviews": "40.9k",
  "tags": "",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "kiwi",
  "name": "Kiwi",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "3 pcs",
  "price": 89,
  "mrp": 120,
  "img": "img/kiwi.webp",
  "rating": 4.5,
  "reviews": "29.8k",
  "tags": "",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "pomegranate",
  "name": "Pomegranate",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "2 pcs (approx. 400 g)",
  "price": 109,
  "mrp": 140,
  "img": "img/pomegranate.webp",
  "rating": 4.1,
  "reviews": "17.6k",
  "tags": "anar",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "papaya",
  "name": "Papaya",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "1 pc (approx. 800 g)",
  "price": 59,
  "mrp": 75,
  "img": "img/papaya.webp",
  "rating": 4.6,
  "reviews": "14.3k",
  "tags": "papita",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "pear",
  "name": "Pear",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "4 pcs (approx. 500 g)",
  "price": 99,
  "mrp": 125,
  "img": "img/pear.webp",
  "rating": 4.6,
  "reviews": "6.5k",
  "tags": "nashpati",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "avocado",
  "name": "Avocado",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "1 pc",
  "price": 129,
  "mrp": 160,
  "img": "img/avocado.webp",
  "rating": 4.8,
  "reviews": "16.5k",
  "tags": "",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "blueberry",
  "name": "Blueberry",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "fruit",
  "unit": "125 g",
  "price": 199,
  "mrp": 249,
  "img": "img/blueberry.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "",
  "about": "Ripe, hand-sorted fruit. Wash before eating."
 },
 {
  "id": "coriander",
  "name": "Coriander leaves",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "100 g",
  "price": 12,
  "mrp": 18,
  "img": "img/coriander.webp",
  "rating": 4.4,
  "reviews": "36.5k",
  "tags": "dhaniya",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "ginger",
  "name": "Ginger",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "100 g",
  "price": 18,
  "mrp": 24,
  "img": "img/ginger.webp",
  "rating": 4.3,
  "reviews": "27.6k",
  "tags": "adrak",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "garlic",
  "name": "Garlic",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "100 g",
  "price": 26,
  "mrp": 34,
  "img": "img/garlic.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "lehsun",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "chilli",
  "name": "Green chilli",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "100 g",
  "price": 14,
  "mrp": 18,
  "img": "img/chilli.webp",
  "rating": 4.2,
  "reviews": "2.1k",
  "tags": "hari mirch",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "lemon",
  "name": "Lemon",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "4 pcs",
  "price": 29,
  "mrp": 36,
  "img": "img/lemon.webp",
  "rating": 4.5,
  "reviews": "29.8k",
  "tags": "nimbu",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "spring-onion",
  "name": "Spring onion",
  "brand": "Farm fresh",
  "cat": "fv",
  "sub": "herbs",
  "unit": "1 bunch",
  "price": 25,
  "mrp": 32,
  "img": "img/spring-onion.webp",
  "rating": 4.5,
  "reviews": "21.0k",
  "tags": "",
  "about": "Fresh kitchen essentials, packed the same day."
 },
 {
  "id": "amul-taaza",
  "name": "Amul Taaza Toned Milk",
  "brand": "Amul",
  "cat": "dairy",
  "sub": "milk",
  "unit": "1 L",
  "price": 72,
  "mrp": 74,
  "img": "img/amul-taaza.webp",
  "rating": 4.3,
  "reviews": "19.8k",
  "tags": "doodh",
  "about": "Keep refrigerated and use before the date on the pack."
 },
 {
  "id": "milk-bottle",
  "name": "Fresh Cow Milk",
  "brand": "Farm fresh",
  "cat": "dairy",
  "sub": "milk",
  "unit": "500 ml bottle",
  "price": 42,
  "mrp": 45,
  "img": "img/milk-bottle.webp",
  "rating": 4.7,
  "reviews": "23.2k",
  "tags": "doodh",
  "about": "Keep refrigerated and use before the date on the pack."
 },
 {
  "id": "amul-butter",
  "name": "Amul Butter, Salted",
  "brand": "Amul",
  "cat": "dairy",
  "sub": "butter",
  "unit": "100 g",
  "price": 60,
  "mrp": 62,
  "img": "img/amul-butter.webp",
  "rating": 4.6,
  "reviews": "14.3k",
  "tags": "makhan",
  "about": "Keep refrigerated. Check the pack for ingredients and allergens."
 },
 {
  "id": "amul-cheese",
  "name": "Amul Cheese Slices",
  "brand": "Amul",
  "cat": "dairy",
  "sub": "butter",
  "unit": "200 g",
  "price": 145,
  "mrp": 155,
  "img": "img/amul-cheese.webp",
  "rating": 4.7,
  "reviews": "23.2k",
  "tags": "",
  "about": "Keep refrigerated. Check the pack for ingredients and allergens."
 },
 {
  "id": "ghee",
  "name": "Banyan Ghee",
  "brand": "Banyan Botanicals",
  "cat": "dairy",
  "sub": "butter",
  "unit": "213 g",
  "price": 449,
  "mrp": 520,
  "img": "img/ghee.webp",
  "rating": 4.4,
  "reviews": "28.7k",
  "tags": "clarified butter",
  "about": "Keep refrigerated. Check the pack for ingredients and allergens."
 },
 {
  "id": "amul-dahi",
  "name": "Amul Masti Dahi",
  "brand": "Amul",
  "cat": "dairy",
  "sub": "curd",
  "unit": "400 g",
  "price": 35,
  "mrp": 38,
  "img": "img/amul-dahi.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "curd yogurt",
  "about": "Keep refrigerated and use within two days of opening."
 },
 {
  "id": "paneer",
  "name": "Govind Malai Paneer",
  "brand": "Govind",
  "cat": "dairy",
  "sub": "curd",
  "unit": "200 g",
  "price": 92,
  "mrp": 105,
  "img": "img/paneer.webp",
  "rating": 4.7,
  "reviews": "39.8k",
  "tags": "cottage cheese",
  "about": "Keep refrigerated and use within two days of opening."
 },
 {
  "id": "bread",
  "name": "White Bread Loaf",
  "brand": "Bakery fresh",
  "cat": "dairy",
  "sub": "bread",
  "unit": "400 g",
  "price": 45,
  "mrp": 50,
  "img": "img/bread.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "pav sandwich",
  "about": "Fresh stock every morning."
 },
 {
  "id": "eggs",
  "name": "Farm Eggs",
  "brand": "Farm fresh",
  "cat": "dairy",
  "sub": "bread",
  "unit": "6 pcs",
  "price": 54,
  "mrp": 66,
  "img": "img/eggs.webp",
  "rating": 4.7,
  "reviews": "31.0k",
  "tags": "anda",
  "about": "Fresh stock every morning."
 },
 {
  "id": "naan",
  "name": "Butter Naan",
  "brand": "Bakery fresh",
  "cat": "dairy",
  "sub": "bread",
  "unit": "2 pcs",
  "price": 59,
  "mrp": 75,
  "img": "img/naan.webp",
  "rating": 4.3,
  "reviews": "27.6k",
  "tags": "roti",
  "about": "Fresh stock every morning."
 },
 {
  "id": "lays",
  "name": "Lay's Classic Salted Chips",
  "brand": "Lay's",
  "cat": "snacks",
  "sub": "chips",
  "unit": "52 g",
  "price": 20,
  "mrp": 20,
  "img": "img/lays.webp",
  "rating": 4.2,
  "reviews": "26.5k",
  "tags": "wafers",
  "about": "Crunchy and ready to eat. Store in a cool, dry place."
 },
 {
  "id": "kurkure",
  "name": "Kurkure Masala Munch",
  "brand": "Kurkure",
  "cat": "snacks",
  "sub": "chips",
  "unit": "82 g",
  "price": 20,
  "mrp": 20,
  "img": "img/kurkure.webp",
  "rating": 4.7,
  "reviews": "23.2k",
  "tags": "namkeen",
  "about": "Crunchy and ready to eat. Store in a cool, dry place."
 },
 {
  "id": "mad-angles",
  "name": "Bingo! Mad Angles Achaari Masti",
  "brand": "Bingo!",
  "cat": "snacks",
  "sub": "chips",
  "unit": "66 g",
  "price": 20,
  "mrp": 20,
  "img": "img/mad-angles.webp",
  "rating": 4.6,
  "reviews": "22.1k",
  "tags": "chips",
  "about": "Crunchy and ready to eat. Store in a cool, dry place."
 },
 {
  "id": "bhujia",
  "name": "Haldiram's Aloo Bhujia",
  "brand": "Haldiram's",
  "cat": "snacks",
  "sub": "chips",
  "unit": "200 g",
  "price": 52,
  "mrp": 60,
  "img": "img/bhujia.webp",
  "rating": 4.7,
  "reviews": "7.6k",
  "tags": "namkeen sev",
  "about": "Crunchy and ready to eat. Store in a cool, dry place."
 },
 {
  "id": "peanuts",
  "name": "Raw Peanuts",
  "brand": "Pantry",
  "cat": "snacks",
  "sub": "chips",
  "unit": "500 g",
  "price": 89,
  "mrp": 110,
  "img": "img/peanuts.webp",
  "rating": 4.7,
  "reviews": "39.8k",
  "tags": "moongfali",
  "about": "Crunchy and ready to eat. Store in a cool, dry place."
 },
 {
  "id": "parle-g",
  "name": "Parle-G Glucose Biscuits",
  "brand": "Parle",
  "cat": "snacks",
  "sub": "biscuits",
  "unit": "800 g",
  "price": 85,
  "mrp": 90,
  "img": "img/parle-g.webp",
  "rating": 4.2,
  "reviews": "18.7k",
  "tags": "biscuit",
  "about": "Good with chai. Store in an airtight box after opening."
 },
 {
  "id": "oreo",
  "name": "Oreo Original Cream Biscuits",
  "brand": "Cadbury",
  "cat": "snacks",
  "sub": "biscuits",
  "unit": "120 g",
  "price": 35,
  "mrp": 40,
  "img": "img/oreo.webp",
  "rating": 4.5,
  "reviews": "37.6k",
  "tags": "biscuit cookie",
  "about": "Good with chai. Store in an airtight box after opening."
 },
 {
  "id": "good-day",
  "name": "Britannia Good Day Cashew Cookies",
  "brand": "Britannia",
  "cat": "snacks",
  "sub": "biscuits",
  "unit": "200 g",
  "price": 38,
  "mrp": 40,
  "img": "img/good-day.webp",
  "rating": 4.5,
  "reviews": "13.2k",
  "tags": "biscuit",
  "about": "Good with chai. Store in an airtight box after opening."
 },
 {
  "id": "hide-seek",
  "name": "Parle Hide & Seek Chocolate Chip Cookies",
  "brand": "Parle",
  "cat": "snacks",
  "sub": "biscuits",
  "unit": "200 g",
  "price": 50,
  "mrp": 55,
  "img": "img/hide-seek.webp",
  "rating": 4.4,
  "reviews": "28.7k",
  "tags": "biscuit",
  "about": "Good with chai. Store in an airtight box after opening."
 },
 {
  "id": "digestive",
  "name": "Digestive Biscuits",
  "brand": "Pantry",
  "cat": "snacks",
  "sub": "biscuits",
  "unit": "250 g",
  "price": 75,
  "mrp": 90,
  "img": "img/digestive.webp",
  "rating": 4.1,
  "reviews": "25.4k",
  "tags": "biscuit",
  "about": "Good with chai. Store in an airtight box after opening."
 },
 {
  "id": "coca-cola",
  "name": "Coca-Cola",
  "brand": "Coca-Cola",
  "cat": "drinks",
  "sub": "soft",
  "unit": "750 ml",
  "price": 40,
  "mrp": 40,
  "img": "img/coca-cola.webp",
  "rating": 4.8,
  "reviews": "40.9k",
  "tags": "coke cold drink",
  "about": "Best served chilled."
 },
 {
  "id": "thums-up",
  "name": "Thums Up",
  "brand": "Coca-Cola",
  "cat": "drinks",
  "sub": "soft",
  "unit": "750 ml",
  "price": 40,
  "mrp": 40,
  "img": "img/thums-up.webp",
  "rating": 4.2,
  "reviews": "34.3k",
  "tags": "cold drink cola",
  "about": "Best served chilled."
 },
 {
  "id": "sprite",
  "name": "Sprite Lime Drink",
  "brand": "Coca-Cola",
  "cat": "drinks",
  "sub": "soft",
  "unit": "750 ml",
  "price": 40,
  "mrp": 40,
  "img": "img/sprite.webp",
  "rating": 4.7,
  "reviews": "39.8k",
  "tags": "cold drink",
  "about": "Best served chilled."
 },
 {
  "id": "pepsi",
  "name": "Pepsi Black",
  "brand": "PepsiCo",
  "cat": "drinks",
  "sub": "soft",
  "unit": "500 ml",
  "price": 38,
  "mrp": 40,
  "img": "img/pepsi.webp",
  "rating": 4.3,
  "reviews": "27.6k",
  "tags": "cold drink cola",
  "about": "Best served chilled."
 },
 {
  "id": "frooti",
  "name": "Frooti Mango Drink",
  "brand": "Parle Agro",
  "cat": "drinks",
  "sub": "juice",
  "unit": "600 ml",
  "price": 36,
  "mrp": 40,
  "img": "img/frooti.webp",
  "rating": 4.6,
  "reviews": "30.9k",
  "tags": "juice aam",
  "about": "Shake well and serve chilled."
 },
 {
  "id": "red-bull",
  "name": "Red Bull Energy Drink",
  "brand": "Red Bull",
  "cat": "drinks",
  "sub": "juice",
  "unit": "250 ml",
  "price": 119,
  "mrp": 125,
  "img": "img/red-bull.webp",
  "rating": 4.5,
  "reviews": "21.0k",
  "tags": "",
  "about": "Shake well and serve chilled."
 },
 {
  "id": "maggi",
  "name": "Maggi 2-Minute Masala Noodles",
  "brand": "Nestlé",
  "cat": "breakfast",
  "sub": "noodles",
  "unit": "280 g (4 pack)",
  "price": 54,
  "mrp": 56,
  "img": "img/maggi.webp",
  "rating": 4.7,
  "reviews": "15.4k",
  "tags": "instant",
  "about": "Ready in minutes. Cooking steps are on the pack."
 },
 {
  "id": "yippee",
  "name": "Sunfeast YiPPee! Magic Masala Noodles",
  "brand": "Sunfeast",
  "cat": "breakfast",
  "sub": "noodles",
  "unit": "240 g (4 pack)",
  "price": 52,
  "mrp": 56,
  "img": "img/yippee.webp",
  "rating": 4.8,
  "reviews": "24.3k",
  "tags": "instant",
  "about": "Ready in minutes. Cooking steps are on the pack."
 },
 {
  "id": "corn-flakes",
  "name": "Kellogg's Corn Flakes Original",
  "brand": "Kellogg's",
  "cat": "breakfast",
  "sub": "cereal",
  "unit": "475 g",
  "price": 189,
  "mrp": 210,
  "img": "img/corn-flakes.webp",
  "rating": 4.7,
  "reviews": "31.0k",
  "tags": "cereal",
  "about": "A quick breakfast with milk or curd."
 },
 {
  "id": "quaker-oats",
  "name": "Quaker Oat So Simple Original",
  "brand": "Quaker",
  "cat": "breakfast",
  "sub": "cereal",
  "unit": "324 g",
  "price": 165,
  "mrp": 199,
  "img": "img/quaker-oats.webp",
  "rating": 4.3,
  "reviews": "35.4k",
  "tags": "oats porridge",
  "about": "A quick breakfast with milk or curd."
 },
 {
  "id": "saffola-oats",
  "name": "Saffola Masala Oats",
  "brand": "Saffola",
  "cat": "breakfast",
  "sub": "cereal",
  "unit": "500 g",
  "price": 179,
  "mrp": 210,
  "img": "img/saffola-oats.webp",
  "rating": 4.1,
  "reviews": "17.6k",
  "tags": "",
  "about": "A quick breakfast with milk or curd."
 },
 {
  "id": "nutella",
  "name": "Nutella Hazelnut Spread",
  "brand": "Ferrero",
  "cat": "breakfast",
  "sub": "spreads",
  "unit": "350 g",
  "price": 349,
  "mrp": 399,
  "img": "img/nutella.webp",
  "rating": 4.4,
  "reviews": "20.9k",
  "tags": "chocolate",
  "about": "Refrigerate after opening."
 },
 {
  "id": "kissan-jam",
  "name": "Kissan Mixed Fruit Jam",
  "brand": "Kissan",
  "cat": "breakfast",
  "sub": "spreads",
  "unit": "500 g",
  "price": 155,
  "mrp": 175,
  "img": "img/kissan-jam.webp",
  "rating": 4.7,
  "reviews": "15.4k",
  "tags": "",
  "about": "Refrigerate after opening."
 },
 {
  "id": "peanut-butter",
  "name": "Pintola High Protein Peanut Butter, Creamy",
  "brand": "Pintola",
  "cat": "breakfast",
  "sub": "spreads",
  "unit": "1 kg",
  "price": 399,
  "mrp": 499,
  "img": "img/peanut-butter.webp",
  "rating": 4.3,
  "reviews": "19.8k",
  "tags": "",
  "about": "Refrigerate after opening."
 },
 {
  "id": "honey",
  "name": "Pure Honey",
  "brand": "Pantry",
  "cat": "breakfast",
  "sub": "spreads",
  "unit": "250 g",
  "price": 149,
  "mrp": 185,
  "img": "img/honey.webp",
  "rating": 4.5,
  "reviews": "5.4k",
  "tags": "shahad",
  "about": "Refrigerate after opening."
 },
 {
  "id": "ketchup",
  "name": "Heinz Tomato Ketchup",
  "brand": "Heinz",
  "cat": "breakfast",
  "sub": "spreads",
  "unit": "435 g",
  "price": 135,
  "mrp": 160,
  "img": "img/ketchup.webp",
  "rating": 4.6,
  "reviews": "6.5k",
  "tags": "sauce",
  "about": "Refrigerate after opening."
 },
 {
  "id": "aashirvaad",
  "name": "Aashirvaad Superior MP Atta",
  "brand": "Aashirvaad",
  "cat": "staples",
  "sub": "grains",
  "unit": "5 kg",
  "price": 245,
  "mrp": 279,
  "img": "img/aashirvaad.webp",
  "rating": 4.4,
  "reviews": "12.1k",
  "tags": "flour wheat",
  "about": "Store in an airtight container away from moisture."
 },
 {
  "id": "india-gate",
  "name": "India Gate Basmati Rice Premium",
  "brand": "India Gate",
  "cat": "staples",
  "sub": "grains",
  "unit": "1 kg",
  "price": 199,
  "mrp": 240,
  "img": "img/india-gate.webp",
  "rating": 4.8,
  "reviews": "24.3k",
  "tags": "chawal",
  "about": "Store in an airtight container away from moisture."
 },
 {
  "id": "toor-dal",
  "name": "Toor Dal",
  "brand": "Pantry",
  "cat": "staples",
  "sub": "dal",
  "unit": "500 g",
  "price": 98,
  "mrp": 120,
  "img": "img/toor-dal.webp",
  "rating": 4.6,
  "reviews": "22.1k",
  "tags": "arhar",
  "about": "Cleaned and sorted. Rinse before cooking."
 },
 {
  "id": "masoor-dal",
  "name": "Origins Red Lentil (Masoor Dal)",
  "brand": "Origins",
  "cat": "staples",
  "sub": "dal",
  "unit": "500 g",
  "price": 85,
  "mrp": 105,
  "img": "img/masoor-dal.webp",
  "rating": 4.5,
  "reviews": "5.4k",
  "tags": "masoor",
  "about": "Cleaned and sorted. Rinse before cooking."
 },
 {
  "id": "fortune-oil",
  "name": "Fortune Sunlite Sunflower Oil",
  "brand": "Fortune",
  "cat": "staples",
  "sub": "oil",
  "unit": "5 L",
  "price": 749,
  "mrp": 865,
  "img": "img/fortune-oil.webp",
  "rating": 4.4,
  "reviews": "12.1k",
  "tags": "tel",
  "about": "Store in a cool, dry place away from sunlight."
 },
 {
  "id": "tata-salt",
  "name": "Tata Salt",
  "brand": "Tata",
  "cat": "staples",
  "sub": "oil",
  "unit": "1 kg",
  "price": 28,
  "mrp": 30,
  "img": "img/tata-salt.webp",
  "rating": 4.4,
  "reviews": "36.5k",
  "tags": "namak",
  "about": "Store in a cool, dry place away from sunlight."
 },
 {
  "id": "everest-garam",
  "name": "Everest Garam Masala",
  "brand": "Everest",
  "cat": "staples",
  "sub": "masala",
  "unit": "100 g",
  "price": 85,
  "mrp": 92,
  "img": "img/everest-garam.webp",
  "rating": 4.3,
  "reviews": "3.2k",
  "tags": "spice",
  "about": "Keep the pack sealed to hold the aroma."
 },
 {
  "id": "turmeric",
  "name": "Nayak's Turmeric Powder",
  "brand": "Nayak's",
  "cat": "staples",
  "sub": "masala",
  "unit": "100 g",
  "price": 38,
  "mrp": 45,
  "img": "img/turmeric.webp",
  "rating": 4.3,
  "reviews": "3.2k",
  "tags": "haldi spice",
  "about": "Keep the pack sealed to hold the aroma."
 },
 {
  "id": "garam-masala",
  "name": "Nayak's Garam Masala Powder",
  "brand": "Nayak's",
  "cat": "staples",
  "sub": "masala",
  "unit": "100 g",
  "price": 72,
  "mrp": 85,
  "img": "img/garam-masala.webp",
  "rating": 4.6,
  "reviews": "30.9k",
  "tags": "spice",
  "about": "Keep the pack sealed to hold the aroma."
 },
 {
  "id": "cardamom",
  "name": "Green Cardamom",
  "brand": "Pantry",
  "cat": "staples",
  "sub": "masala",
  "unit": "50 g",
  "price": 189,
  "mrp": 230,
  "img": "img/cardamom.webp",
  "rating": 4.8,
  "reviews": "16.5k",
  "tags": "elaichi spice",
  "about": "Keep the pack sealed to hold the aroma."
 },
 {
  "id": "cinnamon",
  "name": "Cinnamon Powder",
  "brand": "Pantry",
  "cat": "staples",
  "sub": "masala",
  "unit": "50 g",
  "price": 65,
  "mrp": 80,
  "img": "img/cinnamon.webp",
  "rating": 4.4,
  "reviews": "4.3k",
  "tags": "dalchini spice",
  "about": "Keep the pack sealed to hold the aroma."
 },
 {
  "id": "dairy-milk",
  "name": "Cadbury Dairy Milk",
  "brand": "Cadbury",
  "cat": "sweets",
  "sub": "choc",
  "unit": "50 g",
  "price": 45,
  "mrp": 50,
  "img": "img/dairy-milk.webp",
  "rating": 4.8,
  "reviews": "24.3k",
  "tags": "chocolate",
  "about": "Store in a cool place away from sunlight."
 },
 {
  "id": "kitkat",
  "name": "Nestlé KitKat",
  "brand": "Nestlé",
  "cat": "sweets",
  "sub": "choc",
  "unit": "37 g",
  "price": 28,
  "mrp": 30,
  "img": "img/kitkat.webp",
  "rating": 4.8,
  "reviews": "40.9k",
  "tags": "chocolate",
  "about": "Store in a cool place away from sunlight."
 },
 {
  "id": "five-star",
  "name": "Cadbury 5 Star",
  "brand": "Cadbury",
  "cat": "sweets",
  "sub": "choc",
  "unit": "40 g",
  "price": 20,
  "mrp": 20,
  "img": "img/five-star.webp",
  "rating": 4.6,
  "reviews": "22.1k",
  "tags": "chocolate",
  "about": "Store in a cool place away from sunlight."
 },
 {
  "id": "ferrero",
  "name": "Ferrero Rocher Golden Moments",
  "brand": "Ferrero",
  "cat": "sweets",
  "sub": "choc",
  "unit": "16 pcs",
  "price": 549,
  "mrp": 649,
  "img": "img/ferrero.webp",
  "rating": 4.7,
  "reviews": "31.0k",
  "tags": "chocolate gift",
  "about": "Store in a cool place away from sunlight."
 },
 {
  "id": "royal-dark",
  "name": "Cadbury Royal Dark Chocolate",
  "brand": "Cadbury",
  "cat": "sweets",
  "sub": "choc",
  "unit": "180 g",
  "price": 229,
  "mrp": 275,
  "img": "img/royal-dark.webp",
  "rating": 4.8,
  "reviews": "8.7k",
  "tags": "",
  "about": "Store in a cool place away from sunlight."
 },
 {
  "id": "magnum",
  "name": "Magnum Double Caramel Ice Cream",
  "brand": "Magnum",
  "cat": "sweets",
  "sub": "ice",
  "unit": "4 sticks",
  "price": 299,
  "mrp": 340,
  "img": "img/magnum.webp",
  "rating": 4.5,
  "reviews": "29.8k",
  "tags": "icecream",
  "about": "Delivered frozen. Put it in the freezer straight away."
 },
 {
  "id": "ice-cream-tub",
  "name": "Country Fresh Ice Cream Tub",
  "brand": "Country Fresh",
  "cat": "sweets",
  "sub": "ice",
  "unit": "1 L",
  "price": 249,
  "mrp": 299,
  "img": "img/ice-cream-tub.webp",
  "rating": 4.4,
  "reviews": "12.1k",
  "tags": "icecream",
  "about": "Delivered frozen. Put it in the freezer straight away."
 },
 {
  "id": "red-label",
  "name": "Brooke Bond Red Label Tea",
  "brand": "Brooke Bond",
  "cat": "chai",
  "sub": "tea",
  "unit": "500 g",
  "price": 285,
  "mrp": 310,
  "img": "img/red-label.webp",
  "rating": 4.2,
  "reviews": "10.9k",
  "tags": "chai",
  "about": "Store airtight to keep it fresh."
 },
 {
  "id": "tata-tea",
  "name": "Tata Tea Premium",
  "brand": "Tata",
  "cat": "chai",
  "sub": "tea",
  "unit": "250 g",
  "price": 135,
  "mrp": 150,
  "img": "img/tata-tea.webp",
  "rating": 4.4,
  "reviews": "20.9k",
  "tags": "chai",
  "about": "Store airtight to keep it fresh."
 },
 {
  "id": "nescafe",
  "name": "Nescafé Classic Instant Coffee",
  "brand": "Nestlé",
  "cat": "chai",
  "sub": "coffee",
  "unit": "170 g",
  "price": 499,
  "mrp": 570,
  "img": "img/nescafe.webp",
  "rating": 4.5,
  "reviews": "5.4k",
  "tags": "",
  "about": "Store airtight to keep it fresh."
 },
 {
  "id": "bru",
  "name": "Bru Original Instant Coffee",
  "brand": "Bru",
  "cat": "chai",
  "sub": "coffee",
  "unit": "100 g",
  "price": 245,
  "mrp": 270,
  "img": "img/bru.webp",
  "rating": 4.4,
  "reviews": "12.1k",
  "tags": "",
  "about": "Store airtight to keep it fresh."
 },
 {
  "id": "almonds",
  "name": "Almonds",
  "brand": "Pantry",
  "cat": "chai",
  "sub": "dry",
  "unit": "200 g",
  "price": 229,
  "mrp": 299,
  "img": "img/almonds.webp",
  "rating": 4.1,
  "reviews": "25.4k",
  "tags": "badam",
  "about": "Store airtight. Good for snacking and cooking."
 },
 {
  "id": "cashews",
  "name": "Cashews",
  "brand": "Pantry",
  "cat": "chai",
  "sub": "dry",
  "unit": "200 g",
  "price": 249,
  "mrp": 320,
  "img": "img/cashews.webp",
  "rating": 4.7,
  "reviews": "15.4k",
  "tags": "kaju",
  "about": "Store airtight. Good for snacking and cooking."
 },
 {
  "id": "walnuts",
  "name": "Walnuts in Shell",
  "brand": "Pantry",
  "cat": "chai",
  "sub": "dry",
  "unit": "250 g",
  "price": 219,
  "mrp": 280,
  "img": "img/walnuts.webp",
  "rating": 4.8,
  "reviews": "32.1k",
  "tags": "akhrot",
  "about": "Store airtight. Good for snacking and cooking."
 },
 {
  "id": "raisins",
  "name": "Raisins",
  "brand": "Pantry",
  "cat": "chai",
  "sub": "dry",
  "unit": "200 g",
  "price": 99,
  "mrp": 130,
  "img": "img/raisins.webp",
  "rating": 4.6,
  "reviews": "22.1k",
  "tags": "kishmish",
  "about": "Store airtight. Good for snacking and cooking."
 }
];
